Repository CfM47/TechnicalDowntimeManager-BE, pull requests merged in 2025-01, with the labels that each got.

#103 Optimize query performance with multiple joins
  src/Interfaces/IDepartmentModel.ts
  src/Interfaces/IDowntimeModel.ts
  src/Interfaces/IEquipmentModel.ts
  src/Interfaces/IMaintenanceModel.ts
  src/Interfaces/IRateModel.ts
  src/Interfaces/IRepository.ts
  src/Interfaces/IRoleModel.ts
  src/Interfaces/ITechnicianModel.ts
  src/Interfaces/ITransferModel.ts
  src/Interfaces/IUserModel.ts
  src/features/Department/model.ts
  src/features/Department/types.ts
  src/features/Downtime/model.ts
  src/features/Downtime/schema.ts
  src/features/Downtime/types.ts
  src/features/Equipment/model.ts
  src/features/Equipment/schema.ts
  src/features/Equipment/types.ts
  src/features/Maintenance/model.ts
  src/features/Maintenance/schema.ts
  src/features/Maintenance/types.ts
  src/features/Rate/model.ts
  src/features/Rate/schema.ts
  src/features/Rate/types.ts
  src/features/Role/model.ts
  src/features/Role/types.ts
  src/features/Technician/model.ts
  src/features/Technician/types.ts
  src/features/Transfer/model.ts
  src/features/Transfer/schema.ts
  src/features/Transfer/types.ts
  src/features/User/model.ts
  src/features/User/types.ts
Labels: enhancement

#105 added endpoint auth
  src/features/Auth/router.ts
  src/router.ts
Labels: enhancement

#106 added token sesion to user schema
  src/features/User/schema.ts
Labels: enhancement

#107 Add JWT authentication and user retrieval from token in AuthController
  package.json
  pnpm-lock.yaml
  src/Interfaces/IUserModel.ts
  src/features/Auth/controller.ts
  src/features/Auth/router.ts
  src/features/Auth/utils.ts
  src/features/User/model.ts
  src/features/User/utils.ts
  src/router.ts
Labels: enhancement

#108 Singleton pattern implemented for database connection
  src/db/config/db_connect.ts
Labels: enhancement

#111 updating testing and swagger
  jest.config.ts
  src/features/Department/router.ts
  src/features/Department/test/department.test.ts
  src/features/Downtime/router.ts
  src/features/Downtime/test/downtime.test.ts
  src/features/Equipment/router.ts
  src/features/Equipment/test/equipment.test.ts
  src/features/Maintenance/router.ts
  src/features/Maintenance/test/maintenance.test.ts
  src/features/Rate/router.ts
  src/features/Rate/test/rate.test.ts
  src/features/Role/router.ts
  src/features/Technician/router.ts
  src/features/Technician/test/technician.test.ts
  src/features/Transfer/router.ts
  src/features/Transfer/test/transfer.test.ts
  src/features/User/test/user.test.ts
Labels: enhancement

#119 added enums to schemas equipment maintenance rate and transfer
  src/features/Equipment/utils.ts
  src/features/Maintenance/utils.ts
  src/features/Rate/utils.ts
  src/features/Transfer/utils.ts
Labels: Sprint Plan

#121 added filters to getAll functions
  src/Interfaces/IRepository.ts
  src/features/Department/controller.ts
  src/features/Department/model.ts
  src/features/Downtime/controller.ts
  src/features/Downtime/model.ts
  src/features/Equipment/controller.ts
  src/features/Equipment/model.ts
  src/features/Maintenance/controller.ts
  src/features/Maintenance/model.ts
  src/features/Rate/controller.ts
  src/features/Rate/model.ts
  src/features/Role/controller.ts
  src/features/Role/model.ts
  src/features/Technician/controller.ts
  src/features/Technician/model.ts
  src/features/Transfer/controller.ts
  src/features/Transfer/model.ts
  src/features/User/controller.ts
  src/features/User/model.ts
Labels: enhancement

#122 updated downtime zod schema
  .gitignore
  src/features/Downtime/utils.ts
Labels: enhancement

#123 Removed role entity
  drizzle.config.ts
  src/Interfaces/IRoleModel.ts
  src/enums.ts
  src/features/Auth/controller.ts
  src/features/Role/controller.ts
  src/features/Role/model.ts
  src/features/Role/router.ts
  src/features/Role/schema.ts
  src/features/Role/test/role.test.ts
  src/features/Role/types.ts
  src/features/Role/utils.ts
  src/features/Technician/model.ts
  src/features/Technician/types.ts
  src/features/User/model.ts
  src/features/User/schema.ts
  src/features/User/types.ts
  src/features/User/utils.ts
  src/index.ts
  src/router.ts
  src/utils.ts
Labels: enhancement

#124 Refactor enums
  src/enums.ts
  src/features/Downtime/schema.ts
  src/features/Downtime/utils.ts
  src/features/Equipment/schema.ts
  src/features/Equipment/types.ts
  src/features/Equipment/utils.ts
  src/features/Maintenance/schema.ts
  src/features/Maintenance/utils.ts
  src/features/Transfer/schema.ts
  src/features/Transfer/types.ts
  src/features/Transfer/utils.ts
Labels: refactor

#129 added pagination to getAll functions
  src/Interfaces/IRepository.ts
  src/features/Department/controller.ts
  src/features/Department/model.ts
  src/features/Downtime/controller.ts
  src/features/Downtime/model.ts
  src/features/Equipment/controller.ts
  src/features/Equipment/model.ts
  src/features/Maintenance/controller.ts
  src/features/Maintenance/model.ts
  src/features/Rate/controller.ts
  src/features/Rate/model.ts
  src/features/Technician/controller.ts
  src/features/Technician/model.ts
  src/features/Transfer/controller.ts
  src/features/Transfer/model.ts
  src/features/User/controller.ts
  src/features/User/model.ts
  src/utils.ts
Labels: enhancement

#132 added seed script
  package.json
  src/seed.ts
Labels: enhancement

#136 PDFReportPlugin added
  package.json
  pnpm-lock.yaml
  src/app.ts
  src/core/IPlugin.ts
  src/core/PluginManager.ts
  src/plugins/PDFReportPlugin.ts
Labels: enhancement

#137 Update UserController logic to handle user creation, retrieval, updat…
  src/features/User/controller.ts
  src/features/User/router.ts
  src/features/User/utils.ts
  src/router.ts
Labels: enhancement

#141 Refactor RateController logic and improve validation checks
  src/features/Rate/controller.ts
  src/features/Rate/router.ts
  src/router.ts
Labels: enhancement

#145 downtime report listing last year implemented
  package.json
  src/features/Report/DowntimeReport/controller.ts
  src/features/Report/DowntimeReport/router.ts
  src/router.ts
Labels: enhancement

#146 adding downtime businessLogic
  src/features/Downtime/controller.ts
  src/features/Downtime/router.ts
  src/router.ts
Labels: enhancement

#148 adding maintenance businessLogic
  src/features/Maintenance/controller.ts
  src/features/Maintenance/router.ts
  src/router.ts
Labels: enhancement

#149 added orderBy and sort to getAll functions
  src/Interfaces/IRepository.ts
  src/features/Downtime/model.ts
  src/features/Equipment/controller.ts
  src/features/Equipment/model.ts
  src/features/Equipment/types.ts
  src/features/Maintenance/model.ts
  src/features/Rate/controller.ts
  src/features/Rate/model.ts
  src/features/Rate/types.ts
  src/features/Technician/model.ts
  src/features/Transfer/model.ts
  src/features/User/model.ts
Labels: enhancement

#150 added paginated response to all getAll functions
  src/Interfaces/IRepository.ts
  src/features/Department/model.ts
  src/features/Downtime/model.ts
  src/features/Equipment/model.ts
  src/features/Maintenance/model.ts
  src/features/Rate/model.ts
  src/features/Technician/model.ts
  src/features/Transfer/model.ts
  src/features/User/model.ts
  src/utils.ts
Labels: enhancement

#152 refactored downtime lastyear report, moved from src/Report to src/fea…
  src/Interfaces/IDowntimeModel.ts
  src/features/Downtime/controller.ts
  src/features/Downtime/model.ts
  src/features/Downtime/router.ts
  src/features/Downtime/types.ts
  src/features/Report/DowntimeReport/controller.ts
  src/features/Report/DowntimeReport/router.ts
  src/router.ts
Labels: refactor

#154 state renamed for status in src/features/Equipment/utils.ts
  src/features/Equipment/utils.ts
Labels: bug

#155 .status added in line 53 of src/features/Equipment/utils.ts
  src/features/Equipment/utils.ts
Labels: bug

#157 updated seed script with more information
  src/seed.ts
Labels: enhancement
